# docker-compose -f deploy/docker-compose.yml run --rm terraform init
version: '3.11'
services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}